---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.94, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Session-Token
no_index:
  directory:
    - t
    - inc
requires:
  Getopt::Long: 0
  Session::Token: 0
resources:
  bugtracker: https://github.com/hoytech/App-Session-Token/issues
  repository: git://github.com/hoytech/App-Session-Token.git
version: 0.100
